version: '3.8'

services:
  kali-ui:
    image: kalilinux/kali-rolling
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5901" # This will expose the port to the host
    command: ["/start.sh"]
    networks:
      kali_net:
        ipv4_address: 172.30.0.5 # Specify a fixed IP if needed or let Docker assign one

networks:
  kali_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24 # Custom subnet
