version: '3.8'

services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kali_container
    tty: true
    volumes:
      - ./data:/data  # Mount a local directory to persist data
    networks:
      - kali_net

networks:
  kali_net:
    driver: bridge
